[general]
import = [
  "~/.config/ohmydebn/current/theme/alacritty.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[terminal]
shell = "/usr/bin/zsh"

[window]
opacity = 0.97  # Values from 0.0 (fully transparent) to 1.0 (opaque)
padding.x = 14
padding.y = 14
decorations = "Full"
